### ISSUE TITLE
Gigabot sometimes not connecting or dropping connection

### ISSUE THREAD

**Issue by jim-thompson** [re3Dprinting/touchscreen#32]
Multiple times I've seen the Gigabot connect (confirmed by the fact that it restarts and displays Viki splash screens) but it doesn't send the list of SD files, or respond to other commands.

**Comment by blinkenjim** [comment]
Unable to recreate. In testing, the SD files are always sent.

**Comment by jim-thompson** [comment]
Unable to recreate. In recent testing, the SD file list is always sent/received.
