### ISSUE TITLE
Visual: fix duplicate tags on menu screen

### ISSUE THREAD

**Issue by Alemontfer1992** [re3Dprinting/touchscreen#49]
We should delete the "re:3Display" on the upper left corner of the menu screen because we already have it on the opposite corner. 

<img width="1068" alt="Screen Shot 2020-02-17 at 3 31 16 PM" src="https://user-images.githubusercontent.com/60668348/74681744-8e27ae00-519a-11ea-9eb6-76034dafed18.png">

**Comment by jim-thompson** [comment]
The one in the lower corner has been replaced by an information string listing things like the touchscreen's IP address and the Git commit it was built from.

**Comment by Alemontfer1992** [comment]
I think we should just remove it. It's redundant: we know it is a display and the re:3D logo is there, branding this display as the re:3D display

**Comment by plloppii** [comment]
fixed in latest devs, devel/1.0.28
