### ISSUE TITLE
Visual: use regular re:3D logo

### ISSUE THREAD

**Issue by Alemontfer1992** [re3Dprinting/touchscreen#50]
The logo we currently have on the screen looks like our old stickers: 

<img width="1055" alt="Screen Shot 2020-02-17 at 3 33 34 PM" src="https://user-images.githubusercontent.com/60668348/74681878-e2329280-519a-11ea-9891-ebfbcaa7aee9.png">

I think we should use a regular borderless black re:3D logo for a cleaner look:

<img width="200" alt="Screen Shot 2020-02-17 at 3 34 44 PM" src="https://user-images.githubusercontent.com/60668348/74681944-0bebb980-519b-11ea-94f1-71320673aeb5.png">

**Comment by jim-thompson** [comment]
Agreed, but I'd like to hold off on this until we review the entire UI.

**Comment by jim-thompson** [comment]
Fixed to use the recommended logo.
