### ISSUE TITLE
Visual: Icons are a bit confusing

### ISSUE THREAD

**Issue by Alemontfer1992** [re3Dprinting/touchscreen#51]
There are a couple of icons that are just really confusing. The first time I looked at these screens, this is what I instantly translated each icon into:

<img width="997" alt="Screen Shot 2020-02-17 at 3 40 55 PM" src="https://user-images.githubusercontent.com/60668348/74682283-fdea6880-519b-11ea-83f7-a9277bc4798e.png">

<img width="808" alt="Screen Shot 2020-02-17 at 3 53 34 PM" src="https://user-images.githubusercontent.com/60668348/74682880-afd66480-519d-11ea-9c34-e5a17c075a0e.png">

In that same order, this is what I would expect from those categories:
- Print file: print my file
- Movement: move the bed and print head
- Temperature: preheat extruder/bed
- Settings: all options for printer tuning/calibration 

- Connectivity: connect to wifi, printer, etc.
- Murder: explode printer

**Comment by jim-thompson** [comment]
LOL! Not murder. That's the icon for the serial port setup screen. Serial port / serial killer. So just a little murdery.

**Comment by jim-thompson** [comment]
But I totally agree that the icons aren't very good. Matthew and I have talked about doing a complete visual redesign, and that would rely heavily on you!

**Comment by Alemontfer1992** [comment]
I would be more than happy to help you with the icons and visual aspect of it.

**Comment by plloppii** [comment]
Patched during the latest devs, updating the icons.
