### ISSUE TITLE
Update list not showing some releases.

### ISSUE THREAD

**Issue by jim-thompson** [re3Dprinting/touchscreen#70]
As of right now (Friday 3/20 10:40 am CDT) the list of available updates on the User Update screen is only showing beta/TestFeature as an available release. Several older releases and one newer beta are not shown.

I will refrain from doing anymore release tagging until Noah has a chance to investigate.

**Comment by plloppii** [comment]
Should be patched in the branch "bugfix/user-update"
Please check it out when you get a chance.
