### ISSUE TITLE
Touchscreen crash on Babystepping

### ISSUE THREAD

**Issue by re3dCharlotte** [re3Dprinting/touchscreen#78]
On Gb3-525, I was approximately 2 mins into a print. (April 13, 5:48pm) Touched the baby stepping up arrow and the touch screen went black then restarted to menu screen. The print stopped.
Reconnected, restarted the print, touched babystepping up arrow, and the same issue happened again.
I added a log marker both times.

**Comment by jim-thompson** [comment]
Found the problem. I'm going to install a fix Thursday morning (4/16), so if you could please try babystepping again sometime after that, and please let me know how it goes?

**Comment by re3dCharlotte** [comment]
Thanks Jim. I won't be there until this evening, so I've included Aubrey
and Matthew in case they want to test out babystepping on the touchscreen
before that.


[image:
https://re3d.org/covid-19-update-operations-serving-educators-joining-the-fight/]
<https://re3d.org/covid-19-update-operations-serving-educators-joining-the-fight/>
<https://re3d.org/careers/>

**Comment by jim-thompson** [comment]
Fix is not active an all the printers. I'll be in early Friday to update the inactive printers.
