### ISSUE TITLE
Printer Not Extruding

### ISSUE THREAD

**Issue by SamReeve** [re3Dprinting/touchscreen#91]
The touchscreen was just turned on and connected to the printer. E0 was hot and was heated up via touchscreen. When I taped the down arrow to extrude E0 at the default 10mm, nothing happened. E2 and Z wouldn't move either. X did move and E still didn't move. I set E to 1mm at a time and then it moved. Then I could set it to 10mm at a time and it worked.

**Comment by re3Dprinting** [comment]
Samantha,

Can you replicate this with the latest version 1.0.26 and let me know the results.

Thanks,
Matthew

**Comment by re3Dprinting** [comment]
Version b 1.0.0
verified extrusion is working
