### ISSUE TITLE
Software crash - Accessing DE calibration while printing

### ISSUE THREAD

**Issue by chief-hacker** [re3Dprinting/touchscreen#92]
While printing - If you press on Settings -> DE Calibration icon, the software crashes

Confirmed. The touchscreen finished a print and I clicked on the DE calibration icon and the system crashed. System rebooted and the I clicked on the DE icon again and it worked that time.

**Comment by plloppii** [comment]
Any update on this issue @chief-hacker?
Is the cause from firmware or the software itself?

**Comment by re3Dprinting** [comment]
The issue is not repeatable. I have seen it twice but physically repeating the steps that caused it to happen does not repeat the same results :(

**Comment by re3Dprinting** [comment]
working in b 1.0.0
